services:
  ubuntu2404:
    build:
      context: .
      args:
        USERNAME: ${COMPOSE_PROJECT_NAME}
        PASSWORD: ${COMPOSE_PROJECT_NAME}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - ${SSH_PORT}:22
    shm_size: "16gb"
    ulimits:
      memlock: -1
      stack: 67108864
