services:
  ubuntu2404:
    build:
      context: .
      args:
        USERNAME: ${COMPOSE_PROJECT_NAME}
        PASSWORD: ${COMPOSE_PROJECT_NAME}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    ports:
      - ${SSH_PORT}:22
